<#
.SYNOPSIS
    Keeps the skill router in sync with what is actually on disk.

.DESCRIPTION
    Reads Skills/skills-map.json, scans every SKILL.md under the configured scan
    roots, and regenerates two things:

      1. The AUTOGEN block inside Skills/SKILLS_INDEX.md (the full path table).
      2. The pointer skills under .claude/skills/ used by Claude Code.

    Everything outside the AUTOGEN markers in SKILLS_INDEX.md is hand written and
    is never touched.

    Run this after pulling an update into any repo under Skills/CodeSkills/.

.PARAMETER Check
    Do not write anything. Exit 1 if the generated output would differ from what
    is on disk, or if any path referenced by the router no longer exists.

.EXAMPLE
    powershell -ExecutionPolicy Bypass -File Skills/scripts/sync-skills.ps1
    powershell -ExecutionPolicy Bypass -File Skills/scripts/sync-skills.ps1 -Check
#>
[CmdletBinding()]
param(
    [switch]$Check
)

$ErrorActionPreference = 'Stop'

$RepoRoot  = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$MapPath   = Join-Path $RepoRoot 'Skills\skills-map.json'
$IndexPath = Join-Path $RepoRoot 'Skills\SKILLS_INDEX.md'
$SkillsDir = Join-Path $RepoRoot '.claude\skills'

$BeginMarker = '<!-- BEGIN:AUTOGEN - regenerated by Skills/scripts/sync-skills.ps1 - do not edit by hand -->'
$EndMarker   = '<!-- END:AUTOGEN -->'

$script:Problems = @()
function Add-Problem([string]$Message) { $script:Problems += $Message }

function Write-Utf8NoBom([string]$Path, [string]$Content) {
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8)
}

function Get-RelPath([string]$FullPath) {
    $rel = $FullPath.Substring($RepoRoot.Length).TrimStart('\', '/')
    return $rel.Replace('\', '/')
}

# --- frontmatter -------------------------------------------------------------

function Get-Frontmatter([string]$Path) {
    $lines = [System.IO.File]::ReadAllLines($Path)
    if ($lines.Count -eq 0 -or $lines[0].Trim() -ne '---') { return $null }

    $result = @{ name = ''; description = '' }
    $currentKey = $null

    for ($i = 1; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line.Trim() -eq '---') { break }

        if ($line -match '^([A-Za-z0-9_-]+):\s*(.*)$') {
            $currentKey = $matches[1].ToLower()
            $value      = $matches[2]
            if ($result.ContainsKey($currentKey)) { $result[$currentKey] = $value }
        }
        elseif ($currentKey -and $line -match '^\s+\S' -and $result.ContainsKey($currentKey)) {
            # folded / continued value
            $result[$currentKey] = ($result[$currentKey] + ' ' + $line.Trim()).Trim()
        }
    }

    foreach ($k in @('name', 'description')) {
        $v = $result[$k].Trim()
        if ($v.Length -ge 2) {
            if (($v.StartsWith('"') -and $v.EndsWith('"')) -or ($v.StartsWith("'") -and $v.EndsWith("'"))) {
                $v = $v.Substring(1, $v.Length - 2)
            }
        }
        $result[$k] = $v.Trim()
    }
    return $result
}

# Compress a long upstream description into a short "use when" trigger cell.
function Get-Trigger([string]$Description, [int]$MaxLength = 130) {
    if (-not $Description) { return '(no description)' }

    $text = $Description -replace '\s+', ' '
    $text = $text.Trim()

    # Prefer the sentence that says when to use it.
    $sentences = [regex]::Split($text, '(?<=\.)\s+')
    $picked = $sentences | Where-Object { $_ -match '(?i)\buse (when|for|before|after)\b' } | Select-Object -First 1
    if (-not $picked) { $picked = $sentences | Select-Object -First 1 }
    if (-not $picked) { $picked = $text }

    $picked = $picked.Trim()
    if ($picked.Length -gt $MaxLength) {
        $cut = $picked.Substring(0, $MaxLength)
        $lastSpace = $cut.LastIndexOf(' ')
        if ($lastSpace -gt 40) { $cut = $cut.Substring(0, $lastSpace) }
        $picked = $cut.TrimEnd(',', ';', '.', ' ') + '...'
    }
    return ($picked -replace '\|', '/')
}

function Get-GroupLabel([string]$RelPath) {
    switch -Regex ($RelPath) {
        'CodeSkills/01_Workflow/'                        { return '01_Workflow - process and methodology'; }
        'CodeSkills/02_UI_UX_Design/taste-skill/'        { return '02_UI_UX_Design / taste-skill - visual direction'; }
        'CodeSkills/02_UI_UX_Design/ui-ux-pro-max-skill/'{ return '02_UI_UX_Design / ui-ux-pro-max - product UI intelligence'; }
        'CodeSkills/03_EngineeringQuality/'              { return '03_EngineeringQuality - engineering quality gates'; }
        'CodeSkills/05_AIPoweredLMS/'                    { return '05_AIPoweredLMS - THIS PROJECT (domain, rules, use cases)'; }
        default                                          { return 'Other'; }
    }
}

# --- load map ----------------------------------------------------------------

if (-not (Test-Path $MapPath)) { throw "Missing $MapPath" }
# Read as UTF-8 explicitly: Windows PowerShell 5.1's Get-Content defaults to the system ANSI
# codepage for files without a BOM, which mangles the Vietnamese descriptions into mojibake.
$mapJson = [System.IO.File]::ReadAllText($MapPath, [System.Text.Encoding]::UTF8)
$map = $mapJson | ConvertFrom-Json

# --- scan --------------------------------------------------------------------

$entries = @()
foreach ($root in $map.scanRoots) {
    $full = Join-Path $RepoRoot ($root -replace '/', '\')
    if (-not (Test-Path $full)) { Add-Problem "scanRoot does not exist: $root"; continue }

    Get-ChildItem -Path $full -Recurse -Filter 'SKILL.md' -File | ForEach-Object {
        $rel = Get-RelPath $_.FullName
        $fm  = Get-Frontmatter $_.FullName
        if (-not $fm) { Add-Problem "No YAML frontmatter: $rel"; return }
        if (-not $fm.name) { Add-Problem "Frontmatter has no name: $rel"; return }

        $entries += [PSCustomObject]@{
            Path    = $rel
            Name    = $fm.name
            Trigger = Get-Trigger $fm.description
            Group   = Get-GroupLabel $rel
        }
    }
}

foreach ($p in $map.stackRules) {
    if (-not (Test-Path (Join-Path $RepoRoot ($p -replace '/', '\')))) { Add-Problem "stackRule does not exist: $p" }
}

# --- build the AUTOGEN table -------------------------------------------------

$groupOrder = @(
    '05_AIPoweredLMS - THIS PROJECT (domain, rules, use cases)',
    '01_Workflow - process and methodology',
    '03_EngineeringQuality - engineering quality gates',
    '02_UI_UX_Design / ui-ux-pro-max - product UI intelligence',
    '02_UI_UX_Design / taste-skill - visual direction',
    'Other'
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine($BeginMarker)
[void]$sb.AppendLine()
[void]$sb.AppendLine("Total skills on disk: $($entries.Count). Paths are relative to the workspace root.")
[void]$sb.AppendLine("Open a skill by its **path**. Do not try to guess the path from the skill name - the folder name and the ``name:`` field differ for many of these.")

foreach ($group in $groupOrder) {
    $rows = $entries | Where-Object { $_.Group -eq $group } | Sort-Object Path
    if (-not $rows) { continue }

    [void]$sb.AppendLine()
    [void]$sb.AppendLine("#### $group")
    [void]$sb.AppendLine()
    [void]$sb.AppendLine('| Path (read this) | `name:` | Use when |')
    [void]$sb.AppendLine('| --- | --- | --- |')
    foreach ($r in $rows) {
        [void]$sb.AppendLine("| ``$($r.Path)`` | ``$($r.Name)`` | $($r.Trigger) |")
    }
}

[void]$sb.AppendLine()
[void]$sb.Append($EndMarker)
$autogen = $sb.ToString()

# --- splice into SKILLS_INDEX.md ---------------------------------------------

if (-not (Test-Path $IndexPath)) { throw "Missing $IndexPath" }
$indexRaw = [System.IO.File]::ReadAllText($IndexPath).Replace("`r`n", "`n")

$beginIdx = $indexRaw.IndexOf($BeginMarker)
$endIdx   = $indexRaw.IndexOf($EndMarker)
if ($beginIdx -lt 0 -or $endIdx -lt 0 -or $endIdx -lt $beginIdx) {
    throw "AUTOGEN markers not found in Skills/SKILLS_INDEX.md. Expected:`n$BeginMarker`n...`n$EndMarker"
}

$newIndex = $indexRaw.Substring(0, $beginIdx) + $autogen.Replace("`r`n", "`n") + $indexRaw.Substring($endIdx + $EndMarker.Length)

# --- validate every path the router mentions ---------------------------------

$referenced = [regex]::Matches($newIndex, '(?<![\w/.-])(Skills/CodeSkills/[^\s`|)*]+)') |
              ForEach-Object { $_.Groups[1].Value.TrimEnd('.', ',', ')') } |
              Sort-Object -Unique

foreach ($ref in $referenced) {
    if (-not (Test-Path (Join-Path $RepoRoot ($ref -replace '/', '\')))) {
        Add-Problem "SKILLS_INDEX.md references a path that does not exist: $ref"
    }
}

# --- build pointer skills ----------------------------------------------------

$pointerFiles = @{}
foreach ($p in $map.pointerSkills) {
    $srcFull = Join-Path $RepoRoot ($p.source -replace '/', '\')
    if (-not (Test-Path $srcFull)) {
        Add-Problem "pointerSkill '$($p.name)' points at a missing file: $($p.source)"
        continue
    }

    # Always quote: descriptions contain ': ' which is invalid in a bare YAML scalar.
    $desc = ($p.description -replace '\\', '\\' -replace '"', '\"') -replace '\s+', ' '

    $body = New-Object System.Text.StringBuilder
    [void]$body.AppendLine('---')
    [void]$body.AppendLine("name: $($p.name)")
    [void]$body.AppendLine("description: `"$($desc.Trim())`"")
    [void]$body.AppendLine('---')
    [void]$body.AppendLine()
    [void]$body.AppendLine('<!-- Generated by Skills/scripts/sync-skills.ps1 from Skills/skills-map.json. Do not edit. -->')
    [void]$body.AppendLine()
    [void]$body.AppendLine('Read the full skill and follow it in its entirety:')
    [void]$body.AppendLine()
    [void]$body.AppendLine("- ``$($p.source)``")

    if ($p.PSObject.Properties.Name -contains 'also' -and $p.also) {
        $alsoFull = Join-Path $RepoRoot ($p.also -replace '/', '\')
        if (-not (Test-Path $alsoFull)) { Add-Problem "pointerSkill '$($p.name)' has a missing 'also' path: $($p.also)" }
        [void]$body.AppendLine()
        [void]$body.AppendLine('Then apply the project stack rule on top of it:')
        [void]$body.AppendLine()
        [void]$body.AppendLine("- ``$($p.also)``")
    }

    if ($p.PSObject.Properties.Name -contains 'next' -and $p.next) {
        [void]$body.AppendLine()
        [void]$body.AppendLine("When this stage is done, continue with the ``$($p.next)`` skill.")
    }

    [void]$body.AppendLine()
    [void]$body.AppendLine('Do not read any other skill file unless the router in `Skills/SKILLS_INDEX.md` sends you there.')

    $pointerFiles[(Join-Path $SkillsDir "$($p.name)\SKILL.md")] = $body.ToString().Replace("`r`n", "`n")
}

# --- apply or check ----------------------------------------------------------

$drift = @()

if ($indexRaw -ne $newIndex) { $drift += 'Skills/SKILLS_INDEX.md (AUTOGEN table is stale)' }

foreach ($file in $pointerFiles.Keys) {
    $rel = Get-RelPath $file
    if (-not (Test-Path $file)) { $drift += "$rel (missing)"; continue }
    $existing = [System.IO.File]::ReadAllText($file).Replace("`r`n", "`n")
    if ($existing -ne $pointerFiles[$file]) { $drift += "$rel (out of date)" }
}

if (Test-Path $SkillsDir) {
    Get-ChildItem -Path $SkillsDir -Directory | ForEach-Object {
        $expected = Join-Path $_.FullName 'SKILL.md'
        if (-not $pointerFiles.ContainsKey($expected)) {
            $drift += "$(Get-RelPath $_.FullName) (orphan - not in skills-map.json)"
        }
    }
}

if ($Check) {
    if ($script:Problems.Count -gt 0) {
        Write-Host 'BROKEN REFERENCES:' -ForegroundColor Red
        $script:Problems | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    }
    if ($drift.Count -gt 0) {
        Write-Host 'OUT OF SYNC:' -ForegroundColor Yellow
        $drift | ForEach-Object { Write-Host "  - $_" -ForegroundColor Yellow }
        Write-Host 'Re-run without -Check to regenerate.' -ForegroundColor Yellow
    }
    if ($script:Problems.Count -gt 0 -or $drift.Count -gt 0) { exit 1 }

    Write-Host "OK - $($entries.Count) skills indexed, $($pointerFiles.Count) pointer skills, all referenced paths exist." -ForegroundColor Green
    exit 0
}

if ($script:Problems.Count -gt 0) {
    Write-Host 'BROKEN REFERENCES (fix skills-map.json or the index):' -ForegroundColor Red
    $script:Problems | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    exit 1
}

Write-Utf8NoBom $IndexPath $newIndex
foreach ($file in $pointerFiles.Keys) { Write-Utf8NoBom $file $pointerFiles[$file] }

if (Test-Path $SkillsDir) {
    Get-ChildItem -Path $SkillsDir -Directory | ForEach-Object {
        $expected = Join-Path $_.FullName 'SKILL.md'
        if (-not $pointerFiles.ContainsKey($expected)) {
            Write-Host "Removing orphan pointer skill: $(Get-RelPath $_.FullName)" -ForegroundColor Yellow
            Remove-Item -Recurse -Force -Confirm:$false $_.FullName
        }
    }
}

Write-Host "Wrote Skills/SKILLS_INDEX.md ($($entries.Count) skills) and $($pointerFiles.Count) pointer skills in .claude/skills/." -ForegroundColor Green
